### PR TITLE
fixes #5: Update Hawtio and Jolokia

### LINKED ISSUE #5: Update Hawtio and Jolokia dependencies
Both projects have massively improved since we've last updated. We should update again.

If possible, using a dependency, rather than copying in their binaries, would be an improvement.

### PR DESCRIPTION
**Pull request by guusdk**
This replaces the versions of Hawtio and Jolokia with more up-to-date versions.

Note that the Hawtio web application that is now used includes Jolokia, so we need no add that as a separate dependency to this plugin ourselves. One downside of this is that the endpoint where the Jolokia service is exposed changed, from `/jolokia/` to `/hawtio/jolokia/` I'm thinking of addressing that by adding a new plugin, that only adds Jolokia. I can imagine that there is a use-case for having only the JMX-to-HTTP bridge, and none of the pretty UI.

Instead of copying the binary distributions of the third party dependencies, this commit pulls them in through maven.

I've significantly boosted the version number of the plugin, to reflect that it's nearing completion.

It does look prettier :)

image

### CODE REVIEW

**Comment by deleolajide** [comment]
I miss the old dashboard and it was why I was reluctant to upgrade hawtio, but I appreciate the simpler, cleaner look that is responsive and now usable from a mobile device. 

The use of the default hawtio web console for Java that is a distributed as a **.war** deployment unit means that adding client side plugins to create new views is no more possible. Only server-side mbeans can be added and viewed from the default JMX tree. It reminds me of how the war deployment for Jitsi-Meet limited the ability to  extend ofmeet with requested custom features.

A test case for this would be adding Jetty mbeans and viewing Openfire web services performance with the hawtio Jetty plugin. Something I had done before, but seemed to have lost all trace of it.

In any case, thanks for doing this, the upgrade was long over-due and it is good to be in step with active development of Hawtio and Jolokia.

**Comment by guusdk** [comment]
After more digging, I think that I've found that the the update that I did does not prevent anyone from adding more Hawtio plugins. I've illustrated how that is done using the 'simple-plugin' example that's provided by Hawtio. You can find the example here: https://github.com/guusdk/openfire-jmxweb-plugin/commit/6cf687110519b1889656990714e8f2ec772e3e70

**Comment by akrherz** [comment]
@guusdk Is this PR ready or does your last comment imply more work is necessary?

**Comment by guusdk** [comment]
My last comment ment to illustrate that I believe that _no work_ is needed to retain the functionality that @deleolajide would like to retain. I'm happy to merge as-is, if @deleolajide is.

**Comment by deleolajide** [comment]
> I'm happy to merge as-is, if @deleolajide is.

👍

**Pull request merged**
